/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jvlwjgl;

// import core.Game;

import snake.SnakeGame;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());



        SnakeGame.main(args);




        // ui.GameApp.main(args);

        
        // ux.GameApp.main(args);
    }
}
