/**
INSTRUCTIONS: 
    This Java source file was generated by the Gradle 'init' task.

COMPILE & EXECUTE & CLEANUP (Java):

     gradle build
     gradle run
     gradle clean

 */
package jvswing;

import jaydenswing.Pro1;
import jaydenswing.Pro2;
import core.ViewRouter;
import core.BackendView;
import core.BackendController;


import javax.swing.JPanel;
import javax.swing.SwingUtilities;





public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());


        // Starategy.main(args);
        
        // Pro1.main(args);
        // Pro2.main(args);
        
        SwingUtilities.invokeLater(App::start);
    }

    
    /**
     * Create and display the GUI.
     */
    private static void start() {

        ViewRouter router = ViewRouter.getInstance();


        // route 1: init
        JPanel view = new BackendView();
        new BackendController((BackendView) view);
        router.routeView("core/backend", view);




        // route 1: execute
        router.setFrame(BackendView.TITLE, BackendView.SCREEN__WIDTH, BackendView.SCREEN_HEIGHT);
        router.showView("core/backend");
    }

}
