/**
INSTRUCTIONS: 
    This Java source file was generated by the Gradle 'init' task.

COMPILE & EXECUTE & CLEANUP (Java):

     gradle build
     gradle run
     gradle clean

 */
package jvswing;

import jaydenswing.Pro1;
import jaydenswing.Pro2;
import core.ViewRouter;
import core.ViewLinker;
import core.ControllerLinker;
import core.ViewLoader;
import core.ControllerLoader;

import example.ClassLocationDemo;

import javax.swing.JPanel;
import javax.swing.SwingUtilities;





public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());




        // Starategy.main(args);
        
        // Pro1.main(args);
        // Pro2.main(args);
        



        // ClassLocationDemo.main(args);
        SwingUtilities.invokeLater(App::start);
    }

    
    /**
     * Create and display the GUI.
     */
    private static void start() {
        ViewRouter router = ViewRouter.getInstance();
        
        // route 1: init
        ViewLinker linker = new ViewLinker();
        new ControllerLinker(linker);
        router.registerRoute(ViewLinker.getUrl(), linker);
        
        ViewLoader loader = new ViewLoader();
        new ControllerLoader(loader);
        router.registerRoute(ViewLoader.getUrl(), loader);

        // route 1: execute
        // router.showView(ViewLinker.getUrl());
        router.showView(ViewLoader.getUrl());
    }

}
