/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jvlwjgl;

// import core.Game;
// import core.HigherOrLower;

import platformer.PlatformerGame;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());



        // ClickButtonApp.main(args);
//        snake.SnakeGame.main(args);
        PlatformerGame.main(args);

        
        // Test.main(args);







        // HigherOrLower.main(args);


        // ui.GameApp.main(args);

        
        // ux.GameApp.main(args);
    }
}
